variables:
- group: azurecreds

trigger:
- master

stages:
- stage: Provision
  jobs:
  - job: TerraformTasks
    displayName: Terraform Tasks
       
    steps:
       
    #Download azurecreds.conf File
    - task: DownloadSecureFile@1
      displayName: Download azurecreds.conf file
      name: azurecreds
      inputs:
        secureFile: 'azurecreds.conf'

    # Install SSH Key for VM
    - task: InstallSSHKey@0
      displayName: Install SSH key
      inputs:
        knownHostsEntry: 'known_hosts'
        sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7K6Rr6Ms67KGUsdduZbg22Of8xUrRGJqR5K541bG82Booxt32BXHMWBD6541xUeK7cjX/4M5nRmITiZ1353BrTKjd1ZYBquInz/Qyh4tAfLk83aKJtQFdd1QCS0RLhukmuVMTVo1B7WgmAahw/3RRVyhhwHZigGmqY1jiC+mDmj/K00LhLOmy68r2o+aY7bFmtVdS4EpUDI1UlrF4Of1uPeds5eEliDfRDdQ3NGbNCOxo0zrZDyTXoEJZ0YOA+V6cn+6HcbiO5KJLagafmd549HqjgrW4j/vf1MUoATZifYEGRnEAYTZExsegM6g/b0PBrJazWLdONAM6lsqU8prve0BV9HWexaLMOmm19Vp953cEt4+GfWXyNa0jhauz6/stE0EUM0VBI/Q99hvpbVICFzobV4BnkADWbQHhjZYCymWrdN0CRmUm2qxTcq0TzAt3U5DMgMAdh4/HiutrrHvHgF/5RLzQ0Bk6Q0nidwoKsXj5LE+fxEb+PaVQ1wpUfGc= jorge@Platinum'
        sshKeySecureFile: 'id_rsa'

    #Terraform Install
    - task: TerraformInstaller@0
      displayName: Terraform Install
      inputs:
        terraformVersion: '1.0.1'
    
    - script: az account show
      displayName: Az Account Show

    #Terraform Init script
    - script: terraform init -backend-config=$(azurecreds.secureFilePath)
      displayName: Terraform Init
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
    
    #Terraform Apply script
    - script: terraform apply -auto-approve
      displayName: Terraform Apply
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
      env:
        ARM_SUBSCRIPTION_ID: $(subscription_id)
        ARM_CLIENT_ID:       $(client_id)
        ARM_CLIENT_SECRET:   $(client_secret)
        ARM_TENANT_ID:       $(tenant_id)


