trigger:
- master

stages:
- stage: Prework
  jobs:
  - job: InstallDependencies
    displayName: Install Dependencies
    
    steps:

    #Download azurecreds.conf File
    - task: DownloadSecureFile@1
      displayName: Download azurecreds.conf file
      name: azurecreds 
      inputs:
        secureFile: 'azurecreds.conf'
    
    #Install Terraform
    - task: TerraformInstaller@0
      displayName: Terraform Install
      inputs:
        terraformVersion: '1.0.1'

- stage: Provision
  jobs:
  - job: TerraformTasks
    displayName: Terraform Tasks
    
    steps:
    #Terraform Init
    
    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'init'
        commandOptions: '-backend-config=azurecreds.conf'
        backendServiceArm: 'azurermsc'
        backendAzureRmResourceGroupName: 'tstate'
        backendAzureRmStorageAccountName: 'tstate19206'
        backendAzureRmContainerName: 'tstate'
        backendAzureRmKey: 'test.terraform.tfstate'
    
    #Terraform apply
    - task: TerraformTaskV1@0
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: |
          -auto-approve 
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        environmentServiceNameAzureRM: 'azurermsc'