trigger:
- master

stages:

- stage: Provision
  jobs:
  - job: TerraformTasks
    displayName: Terraform Tasks
    steps:
    #Download azurecreds.conf File
    - task: DownloadSecureFile@1
      displayName: Download azurecreds.conf file
      name: azurecreds 
      inputs:
        secureFile: 'azurecreds.conf'

    #Install Terraform
    - task: TerraformInstaller@0
      displayName: Terraform Install
      inputs:
        terraformVersion: '0.13.5'

    #Terraform Init
    - task: TerraformTaskV1@0
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init -backend-config=azurecreds.conf'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
    
    #Terraform apply
    - task: TerraformTaskV1@0
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: |
          -auto-approve 
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        environmentServiceNameAzureRM: 'azurermsc'